### ISSUE TITLE
这个是打码服务器的问题吗

### ISSUE THREAD

**Issue by liuyongly** [hvnobug/12306_ticket#1]
HTTPSConnectionPool(host='12306.yinaoxiong.cn', port=443): Max retries exceeded with url: /verify/base64/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)')))

**Comment by hvnobug** [comment]
如果使用了代理，关闭代理后重试
最好使用自建打码服务器
